export {default as TelegramIcon} from './TelegramIcon'
export {default as InstagramIcon} from './InstagramIcon'
export {default as BaleIcon} from './BaleIcon'
export {default as WhatsAppIcon} from './WhatsAppIcon'
export {default as ShareIcon} from './ShareIcon'